Set Implicit Arguments.

From coqutil Require Import Datatypes.String.
From Stdlib Require Import Lists.List.
Import ListNotations.
Open Scope string.
Open Scope list.
From Utils Require Import Utils.
From Pyrosome Require Import Theory.Core Elab.Elab Tools.Resolution
  Tools.EGraph.ComputeWf Tools.EGraph.TypeInference Tools.EGraph.InjRuleGen.
From Pyrosome.Gluing Require Import CutTModel Eval CutModelSound.
From Pyrosome.Lang Require Import SimpleVSubst SimpleVSTLC SimpleUnit.
Import Core.Notations.

(* Normalization for call-by-value STLC with explicit substitutions.

   The language fixed here is [stlc_unit]: the bare calculus [stlc] plus
   [exp_subst]/[value_subst], extended with [unit_lang], which contributes the
   base type [#"unit"] and its introduction form [#"tt"].  The base type
   matters for more than expressiveness: with a closed meta-context, [ty]
   generated by [->] alone has no base case, so no closed type exists and any
   normalization statement over the bare calculus would be vacuous.
   [stlc_unit] is the language the normalization theorem is actually about.

   The generic driver of Gluing/CutModelSound.v is specialized to it.  Its
   content is the reduction of normalization to model construction: supply a
   [CutTModel] whose [ceq_term t e e] says "e has a normal form at t", and every
   well-typed term of the language has one. *)

(* The unit-extended language: 39 rules.  [unit_lang] contributes [#"unit"],
   [#"tt"], and the substitution-compatibility equation for [tt]. *)
Definition stlc_unit := stlc ++ unit_lang ++ exp_subst ++ value_subst.

Lemma stlc_unit_wf : wf_lang stlc_unit.
Proof. compute_wf_lang. Qed.

Section WithCtx.
  Context (L : lang)
    (Lwf : wf_lang L)
    (c : ctx)
    (wfc : wf_ctx (Model := core_model L) c).

  Context {CM : CutTModel}
    {CMok : CutTModel_ok L c}.

  (* Normalization, modulo the model.  [ceq_term t e e] is whatever content the
     model attaches to a term; for a normalization model that content is its
     normal form, so this says every well-typed term of [L] has one. *)
  Theorem normalization_from_model t e
    : wf_term L c e t ->
      inhabited (ceq_term (CutTModel := CM) t e e).
  Proof.
    intro Hwf.
    eapply (cut_model_normalization Lwf wfc); eassumption.
  Qed.

  (* The equational form: provably-equal terms receive equal content. *)
  Theorem eq_sound t e1 e2
    : eq_term L c t e1 e2 ->
      inhabited (ceq_term (CutTModel := CM) t e1 e2).
  Proof.
    intro Heq.
    eapply (cut_model_inhabited Lwf wfc); eassumption.
  Qed.

End WithCtx.
