Set Implicit Arguments.

From coqutil Require Import Datatypes.String.
From Stdlib Require Import Lists.List.
Import ListNotations.
Open Scope string.
Open Scope list.
From Utils Require Import Utils.
From Pyrosome Require Import Theory.Core.
From Pyrosome.Gluing Require Import CutTModel Eval CutModelSound
  StlcModel StlcNormalization StlcNormalForms StlcEqns StlcLogRel StlcRSub.
From Pyrosome.Lang Require Import SimpleVSubst SimpleVSTLC SimpleUnit.
Import Core.Notations.

(* Layer 4a: the model's relations.

   This file fixes the CONTRACT that the [CutTModel_ok] obligations are proved
   against; it deliberately contains no obligation proofs, so that the
   congruence and equation cases can be developed independently.

   Two design points, both load-bearing:

   - Every clause carries [eq_term stlc_unit [] t e1 e2] as a conjunct.  This is
     the gluing: "has a normal form" means *provably equal to a canonical form*,
     so the substitution equations are discharged inside the theory and no
     confluence/termination argument for the sigma-calculus is needed.  It also
     makes [cterm_trans]/[cterm_sym]/[cterm_conv] nearly free.

   - The semantic conjunct quantifies over REDUCIBLE SUBSTITUTIONS.  It has to
     live here rather than in a separate lemma, because [CutTModel_ok]'s
     [cterm_cong] concludes about the term itself, not about a substitution
     instance -- so closure under reducible substitution must be part of the
     relation.

   Note the semantic conjunct constrains only [e1].  The corresponding fact for
   [e2] is recovered from the equation via [RV_eq]/[RE_eq]/[RSub_eq]; that is
   what [Ceq_term_sym] below does. *)

Local Notation eqt := (eq_term stlc_unit []).
Local Notation wft := (wf_term stlc_unit []).

(* There are no sort equations in this language, so judgemental sort equality is
   generated by congruence alone, and -- since [Ceq_term] at [ty]/[env] forces
   syntactic equality -- plain equality is the right relation.  This makes
   [cterm_conv], [csort_trans] and [csort_sym] immediate. *)
Definition Ceq_sort (t1 t2 : sort) : Prop := t1 = t2.

Definition Ceq_term (t : sort) (e1 e2 : term) : Prop :=
  match t with
  | scon "ty" [] => e1 = e2 /\ TyOk e1
  | scon "env" [] => e1 = e2 /\ EnvOk e1
  | scon "sub" [G'; G] =>
      eqt (Ssub G G') e1 e2
      /\ (forall D h, EnvOk D -> RSub D G h -> RSub D G' (Cmp D G G' h e1))
  | scon "val" [A; G] =>
      eqt (Sval G A) e1 e2
      /\ (forall D g, EnvOk D -> RSub D G g -> RV D A (ValSubst D G g A e1))
  | scon "exp" [A; G] =>
      eqt (Sexp G A) e1 e2
      /\ (forall D g, EnvOk D -> RSub D G g -> RE D A (ExpSubst D G g A e1))
  | _ => False
  end.

(* Clause readings.  Downstream proofs should go through these rather than
   unfolding [Ceq_term], so that a change of representation stays local. *)
Lemma Ceq_ty_iff A1 A2 : Ceq_term Sty A1 A2 <-> (A1 = A2 /\ TyOk A1).
Proof. reflexivity. Qed.

Lemma Ceq_env_iff G1 G2 : Ceq_term Senv G1 G2 <-> (G1 = G2 /\ EnvOk G1).
Proof. reflexivity. Qed.

Lemma Ceq_sub_iff G G' g1 g2
  : Ceq_term (Ssub G G') g1 g2
    <-> (eqt (Ssub G G') g1 g2
         /\ forall D h, EnvOk D -> RSub D G h -> RSub D G' (Cmp D G G' h g1)).
Proof. reflexivity. Qed.

Lemma Ceq_val_iff G A v1 v2
  : Ceq_term (Sval G A) v1 v2
    <-> (eqt (Sval G A) v1 v2
         /\ forall D g, EnvOk D -> RSub D G g -> RV D A (ValSubst D G g A v1)).
Proof. reflexivity. Qed.

Lemma Ceq_exp_iff G A e1 e2
  : Ceq_term (Sexp G A) e1 e2
    <-> (eqt (Sexp G A) e1 e2
         /\ forall D g, EnvOk D -> RSub D G g -> RE D A (ExpSubst D G g A e1)).
Proof. reflexivity. Qed.

(* The model.  [CutTModel]'s carriers are Type-valued; Prop-valued relations are
   accepted by cumulativity, exactly as Gluing/SyntacticModel.v does. *)
Definition StlcCM : CutTModel :=
  {|
    ceq_sort := Ceq_sort;
    ceq_term := Ceq_term;
  |}.
