Require Import WIP.DttModelBase.
Print Assumptions base_cong_obligation.
Print Assumptions base_by_obligation.
Print Assumptions cong_U.
Print Assumptions cong_El.
Print Assumptions cong_Nat.
Print Assumptions cong_zero.
Print Assumptions cong_suc.
Print Assumptions cong_Empty.
Print Assumptions by_U_subst.
Print Assumptions by_El_subst.
Print Assumptions by_Nat_subst.
Print Assumptions by_zero_subst.
Print Assumptions by_suc_subst.
Print Assumptions by_Empty_subst.
