Set Implicit Arguments.

From coqutil Require Import Datatypes.String.
From Stdlib Require Import Lists.List.
Import ListNotations.
Open Scope string.
Open Scope list.
From Utils Require Import Utils.
From Pyrosome Require Import Theory.Core.
Require Import WIP.DttModel WIP.DttNormalForms.
Import Core.Notations.

(* =====================================================================
   LAYER 2: reducibility.

   THE STRUCTURAL PROBLEM.  Stlc/LogRel.v defines [RVarr] as
     [Fixpoint RVarr (G A v : term) {struct A}]
   -- structural recursion on the syntactic TYPE.  That is well founded
   there because [TyOk] is generated by [unit] and [->] over CLOSED syntax
   and the Kripke quantifier ranges over the purely syntactic class [Wk].
   In a dependent theory it fails twice over:

     (a) the codomain of a Pi is [B[<id,a>]], an instantiation, whose size
         is not bounded by the size of [Pi F B]; and
     (b) types contain terms, so no syntactic measure on types decreases
         through the universe clause (the elements of [U r l] are codes of
         unbounded size).

   THE REPLACEMENT.  [RTy G i A P] below is an ORDINARY STRICTLY-POSITIVE
   INDUCTIVE RELATION between a type [A] and a "candidate" [P : term ->
   Prop] -- "A is reducible, and its set of reducible elements is P".  No
   recursion on syntax, no measure, no well-founded recursion, no
   induction-recursion.  Two things make this work:

     - The Pi clause takes the domain candidate [Pd] and the codomain
       candidate family [Pc] as CONSTRUCTOR PARAMETERS.  The hypothesis
       "[a] is a reducible argument" is then [Pd D w a] -- a bound
       variable applied, NOT a recursive occurrence of [RTy].  So the
       negative occurrence that forces induction-recursion in
       Abel-Ohman-Vezzosi is a negative occurrence of a PARAMETER, which
       strict positivity permits.  [RTy] itself appears only as the
       conclusion of universally quantified hypotheses, i.e. strictly
       positively.

     - The universe clause does NOT say "the elements of [U r L0] are the
       reducible types".  It says they are the terms provably equal to a
       SYNTACTIC NORMAL CODE ([NfCode], Layer 1).  That is what breaks the
       would-be negative occurrence of [RTy] in its own universe clause.
       The bridge back -- every normal code names a reducible type -- is
       the separate lemma [RTyEx_of_NfCode] below, proved by a plain
       induction on [NfCode].  This is only sound because Layer 1's normal
       codes are themselves an inductively generated class; it is the
       payoff of stating everything up to [eq_term].

   [RTy] lives in Prop, is eliminable into Prop, and every relation in this
   development is Prop-valued.  That is deliberate: the abandoned
   Lang/OTT/Norm attempt built its logical relations in Type and then could
   not eliminate the Prop-valued [wf_term] into them (the "hard direction"
   was never even stated).  Here the Prop/Type bridge is handled once and
   for all by Gluing/CutModelSound.v's [inhabited], exactly as in the STLC
   proof.

   WHERE THE [eq_term] GUARD MUST *NOT* GO.  The STLC proof's central
   invariant -- every clause carries [eq_term l [] t e1 e2] as a conjunct,
   so "has a normal form" means "provably equal to a canonical form" --
   survives for the SUBJECT and is what makes the substitution equations
   discharge inside the theory.  It must NOT be extended to the TYPE index.

   The tempting design guards each clause by [eq_term (sTy G i) A <canon>],
   making [RTy] invariant under type conversion by construction.  That is
   fatal: ELIMINATION then requires knowing that two different canonical
   types are not convertible -- [Nat] vs [Empty] vs [Pi_rel F B] vs a
   neutral code -- and THAT IS A CONSEQUENCE OF NORMALIZATION, not an input
   to it.  Concretely, no auxiliary syntactic-invariant model can supply it:
   any candidate invariant must be preserved by [snoc_hd]
   ([exp_subst <g,v> hd = v]), which lets a variable's code become [Nat],
   so no substitution-stable head-tag on codes exists in an open context.
   (By contrast the U-vs-El distinction at the sort [ty] IS cheaply
   modellable, since no equation of [ott_dtt] mixes them; but that is not
   enough.)

   SO: the clauses below are guarded SYNTACTICALLY -- [RTy] is stated at the
   canonical type itself, never up to conversion.  The clauses are then
   pairwise disjoint by inspection of the head symbol, and the functionality
   lemma [RTy_fun] is an ordinary induction.  Conversion is absorbed one
   level up: Layer 4's [Ceq_term] at the sort [exp] quantifies UNIVERSALLY
   over normal representatives [A0] of the type,

     forall D g A0, RSub D G g -> TyOk D i A0 -> eq_term (A[g]) A0 ->
                    RTm D i A0 (e[g])

   which makes transfer along a type equation free (both types have the same
   set of normal representatives), while ELIMINATION is by EXHIBITING a
   normal representative -- and every congruence case of Layer 4b can
   exhibit one, from the premises it already has.  This is the single most
   important correction to a naive transposition of the STLC design, and it
   is what removes the need for any sort-injectivity / non-confusion
   development of the kind that sank Lang/OTT/Norm/SortInj.v.
   ===================================================================== *)

Local Notation wft := (wf_term ott_dtt []).
Local Notation eqt := (eq_term ott_dtt []).

(* ------------------------------------------------------------------ *)
(* Syntactic helpers for the Kripke clause                              *)
(* ------------------------------------------------------------------ *)

(* [F] weakened along [w : sub D G], as a code *)
Definition wkCode (D G w r F : term) : term := oExpSubst D G w iU (tU G r) F.

(* the domain type at the weakened stage *)
Definition tDomAt (G rF F D w : term) : term :=
  oTySubst D G w (iE rF) (tEl G rF F).

(* [<w, a> : sub D (extC0 G rF F)] -- the substitution that instantiates the
   binder by [a] after weakening along [w] *)
Definition oSnocAt (G rF F D w a : term) : term :=
  oSnoc D G (iE rF) (tEl G rF F) w a.

(* the codomain type instantiated at [a], for the relevant/irrelevant Pi *)
Definition tCodAtR (G rF F B D w a : term) : term :=
  oTySubst D (oExtC0 G rF F) (oSnocAt G rF F D w a) (iE oRel)
    (oEl (oExtC0 G rF F) oRel oL0 B).
Definition tCodAtI (G rF F B D w a : term) : term :=
  oTySubst D (oExtC0 G rF F) (oSnocAt G rF F D w a) (iE oIrr)
    (oEl (oExtC0 G rF F) oIrr oL0 B).

(* [<w o wkn, hd> : sub (extC0 D rF F[w]) (extC0 G rF F)] -- the lift of [w]
   under the binder.  This is exactly the [under' w] of Lang/OTT/Pi.v's
   substitution-commutation rules, written out. *)
Definition oLiftAt (G rF F D w : term) : term :=
  oSnoc (oExtC0 D rF (wkCode D G w rF F)) G (iE rF) (tEl G rF F)
    (oCmp (oExtC0 D rF (wkCode D G w rF F)) D G
       (oWkn D (iE rF) (tEl D rF (wkCode D G w rF F))) w)
    (oHd D (iE rF) (tEl D rF (wkCode D G w rF F))).

(* [B] lifted along [w] *)
Definition wkCodBody (G rF F D w r B : term) : term :=
  oExpSubst (oExtC0 D rF (wkCode D G w rF F)) (oExtC0 G rF F)
    (oLiftAt G rF F D w) iU (tU (oExtC0 G rF F) r) B.

(* the weakened function, applied to [a], at the weakened stage *)
Definition oAppAtR (G rF F B D w f a : term) : term :=
  oAppRel D rF oL0 oL0 (wkCode D G w rF F) (wkCodBody G rF F D w oRel B)
    (oExpSubst D G w (iE oRel) (tEl G oRel (oPiRel G rF oL0 oL0 F B)) f) a.
Definition oAppAtI (G rF F B D w f a : term) : term :=
  oAppIrr D rF oL0 (wkCode D G w rF F) (wkCodBody G rF F D w oIrr B)
    (oExpSubst D G w (iE oIrr) (tEl G oIrr (oPiIrr G rF oL0 F B)) f) a.

(* "has a normal form at the canonical type" -- the gluing conjunct that
   every clause carries *)
Definition HasNf (G i A e : term) : Prop :=
  exists n, NfET G i A n /\ eqt (sExp G i A) e n.
Definition HasNe (G i A e : term) : Prop :=
  exists n, NeET G i A n /\ eqt (sExp G i A) e n.
Definition HasNfCode (G r e : term) : Prop :=
  exists n, NfCode G r n /\ eqt (sU G r) e n.

(* ------------------------------------------------------------------ *)
(* THE LOGICAL RELATION                                                 *)
(* ------------------------------------------------------------------ *)

Inductive RTy : term -> term -> term -> (term -> Prop) -> Prop :=

(* the universe.  Its elements are the terms provably equal to a normal
   code; reducibility of the type they NAME is recovered separately. *)
| rty_U : forall G r P,
    EnvOk G -> RelNf r ->
    (forall e, P e <-> (HasNfCode G r e /\ wft e (sU G r))) ->
    RTy G iU (tU G r) P

(* a neutral type: only neutrals inhabit it *)
| rty_ne : forall G r n P,
    EnvOk G -> RelNf r ->
    NeET G iU (tU G r) n ->
    (forall e, P e <-> HasNe G (iE r) (tEl G r n) e) ->
    RTy G (iE r) (tEl G r n) P

(* Nat: its normal forms are zero, suc-chains and neutrals, all of which
   Layer 1 already generates, so "reducible" is just "has a normal form" *)
| rty_nat : forall G P,
    EnvOk G ->
    (forall e, P e <-> HasNf G (iE oRel) (tEl G oRel (oNat G)) e) ->
    RTy G (iE oRel) (tEl G oRel (oNat G)) P

(* Empty: no introduction forms, so only neutrals *)
| rty_empty : forall G P,
    EnvOk G ->
    (forall e, P e <-> HasNe G (iE oIrr) (tEl G oIrr (oEmpty G)) e) ->
    RTy G (iE oIrr) (tEl G oIrr (oEmpty G)) P

(* the relevant Pi.  [Pd] and [Pc] are the domain and codomain candidates,
   passed as constructor parameters -- this is what keeps the definition
   strictly positive.  The Kripke quantifier ranges over [Wk], the purely
   syntactic class of Layer 1, exactly as in the STLC proof.

   The domain and codomain types at the weakened/instantiated stage
   ([tDomAt], [tCodAtR]) are NOT syntactically normal, so the clause NAMES a
   normal representative [D0]/[C0] existentially and states the
   sub-derivation there.  Naming rather than universally quantifying is
   load-bearing: [Pd D w] must be THE candidate of ONE normal type, so that
   [RTy_fun] (functionality at a fixed SYNTACTIC type) suffices to identify
   it when the clause is used.  Universally quantifying over all normal
   representatives would instead require them to be pairwise
   non-convertible -- the very fact this design is built to avoid needing.
   Conversely, USING the clause is easy: a hypothesis [RTmN D _ (tDomAt ..)
   a] is instantiated at the named [D0] and matched by [RTy_fun]. *)
| rty_pi_rel : forall G rF F B P
                      (Pd : term -> term -> term -> Prop)
                      (Pc : term -> term -> term -> term -> Prop),
    EnvOk G ->
    NfCode G rF F ->
    NfCode (oExtC0 G rF F) oRel B ->
    (forall D w, Wk D G w -> EnvOk D ->
       exists D0, TyOk D (iE rF) D0
                  /\ eqt (sTy D (iE rF)) (tDomAt G rF F D w) D0
                  /\ RTy D (iE rF) D0 (Pd D w)) ->
    (forall D w a, Wk D G w -> EnvOk D -> Pd D w a ->
       exists C0, TyOk D (iE oRel) C0
                  /\ eqt (sTy D (iE oRel)) (tCodAtR G rF F B D w a) C0
                  /\ RTy D (iE oRel) C0 (Pc D w a)) ->
    (forall e, P e <->
       (HasNf G (iE oRel) (tEl G oRel (oPiRel G rF oL0 oL0 F B)) e
        /\ forall D w a, Wk D G w -> EnvOk D -> Pd D w a ->
             Pc D w a (oAppAtR G rF F B D w e a))) ->
    RTy G (iE oRel) (tEl G oRel (oPiRel G rF oL0 oL0 F B)) P

(* the irrelevant Pi *)
| rty_pi_irr : forall G rF F B P
                      (Pd : term -> term -> term -> Prop)
                      (Pc : term -> term -> term -> term -> Prop),
    EnvOk G ->
    NfCode G rF F ->
    NfCode (oExtC0 G rF F) oIrr B ->
    (forall D w, Wk D G w -> EnvOk D ->
       exists D0, TyOk D (iE rF) D0
                  /\ eqt (sTy D (iE rF)) (tDomAt G rF F D w) D0
                  /\ RTy D (iE rF) D0 (Pd D w)) ->
    (forall D w a, Wk D G w -> EnvOk D -> Pd D w a ->
       exists C0, TyOk D (iE oIrr) C0
                  /\ eqt (sTy D (iE oIrr)) (tCodAtI G rF F B D w a) C0
                  /\ RTy D (iE oIrr) C0 (Pc D w a)) ->
    (forall e, P e <->
       (HasNf G (iE oIrr) (tEl G oIrr (oPiIrr G rF oL0 F B)) e
        /\ forall D w a, Wk D G w -> EnvOk D -> Pd D w a ->
             Pc D w a (oAppAtI G rF F B D w e a))) ->
    RTy G (iE oIrr) (tEl G oIrr (oPiIrr G rF oL0 F B)) P.

(* the derived predicates the rest of the development uses *)
Definition RTyEx (G i A : term) : Prop := exists P, RTy G i A P.
Definition RTm (G i A e : term) : Prop := exists P, RTy G i A P /\ P e.

(* The CONVERSION-CLOSED forms, quantified over normal representatives of
   the type.  These, not [RTy]/[RTm], are what Layer 4's [Ceq_term] uses.
   [RTyN] is "the type has a normal form"; [RTmN] is "the term is reducible
   at EVERY normal representative of its type".  Transfer along a type
   equation is then literally a rewrite of the [eqt] premise, with no
   irrelevance lemma and no non-confusion input. *)
Definition RTyN (G i A : term) : Prop :=
  exists A0, TyOk G i A0 /\ eqt (sTy G i) A A0.
Definition RTmN (G i A e : term) : Prop :=
  forall A0, TyOk G i A0 -> eqt (sTy G i) A A0 -> RTm G i A0 e.

(* ================================================================== *)
(* STATEMENTS ONLY BELOW THIS LINE                                     *)
(* ================================================================== *)

(* ------------------------------------------------------------------ *)
(* FUNCTIONALITY                                                        *)
(*                                                                      *)
(* With syntactic guards this is an ordinary induction: the six clauses  *)
(* are pairwise disjoint by the head symbol of the type ([U] vs [El],    *)
(* and within [El] the head of the code: [Nat], [Empty], [Pi_rel],       *)
(* [Pi_irr], neutral).  Contrast the eq_term-guarded design, where the   *)
(* corresponding statement would be [RTy G i A1 P1 -> RTy G i A2 P2 ->   *)
(* eqt A1 A2 -> ...], which is NOT provable without non-confusion of     *)
(* canonical codes -- a consequence of normalization, not an input.      *)
(* ------------------------------------------------------------------ *)

Lemma RTy_fun G i A P1 P2
  : RTy G i A P1 -> RTy G i A P2 -> forall e, P1 e <-> P2 e.
Admitted.

(* transfer along a type equation: free, by definition of [RTmN] *)
Lemma RTmN_ty_eq G i A A' e
  : RTmN G i A e -> eqt (sTy G i) A A' -> RTmN G i A' e.
Admitted.

Lemma RTyN_ty_eq G i A A' : RTyN G i A -> eqt (sTy G i) A A' -> RTyN G i A'.
Admitted.

(* invariance under provable equality of the TERM -- free from the [HasNf]
   conjunct that every clause carries *)
Lemma RTm_eq G i A e e'
  : RTm G i A e -> eqt (sExp G i A) e e' -> RTm G i A e'.
Admitted.

Lemma RTmN_eq G i A e e'
  : RTmN G i A e -> eqt (sExp G i A) e e' -> RTmN G i A e'.
Admitted.

(* ------------------------------------------------------------------ *)
(* Escape and reflect                                                   *)
(* ------------------------------------------------------------------ *)

Lemma RTy_wf G i A P : RTy G i A P -> wft A (sTy G i).
Admitted.

Lemma RTm_wf G i A e : RTm G i A e -> wft e (sExp G i A).
Admitted.

(* ESCAPE: a reducible term at a NORMAL type has a normal form.  This is
   what the top-level theorem consumes, and it needs no case analysis --
   every clause carries [HasNf] (for [rty_ne]/[rty_empty] via [HasNe], for
   [rty_U] via [HasNfCode] and [nfet_code]). *)
Lemma RTm_escape G i A e
  : RTm G i A e -> TyOk G i A -> HasNf G i A e.
Admitted.

(* REFLECT: a neutral of a reducible type is reducible.  Uniform over the
   clauses again: every candidate admits its neutrals. *)
Lemma RTm_reflect G i A e
  : RTyEx G i A -> HasNe G i A e -> EnvOk G -> RTm G i A e.
Admitted.

(* the special case Layer 3 needs: object-level variables are reducible *)
Lemma RTm_var G i A x
  : VarT G i A x -> EnvOk G -> TyOk G i A -> RTm G i A x.
Admitted.

(* ------------------------------------------------------------------ *)
(* Every normal type is reducible                                       *)
(*                                                                      *)
(* This is the bridge that replaces the negative occurrence of [RTy] in  *)
(* the universe clause.  It is a plain induction on [NfCode]/[TyOk].     *)
(* ------------------------------------------------------------------ *)

Lemma RTyEx_of_NfCode G r e
  : NfCode G r e -> EnvOk G -> RTyEx G (iE r) (tEl G r e).
Admitted.

Lemma RTyEx_of_TyOk G i A : TyOk G i A -> RTyEx G i A.
Admitted.

(* ------------------------------------------------------------------ *)
(* Stability under weakening                                            *)
(* ------------------------------------------------------------------ *)

Lemma RTyN_wk G i A D w
  : RTyN G i A -> Wk D G w -> EnvOk D -> EnvOk G ->
    RTyN D i (oTySubst D G w i A).
Admitted.

Lemma RTmN_wk G i A e D w
  : RTmN G i A e -> RTyN G i A -> Wk D G w -> EnvOk D -> EnvOk G ->
    RTmN D i (oTySubst D G w i A) (oExpSubst D G w i A e).
Admitted.

(* ------------------------------------------------------------------ *)
(* The Pi interface consumed by Layer 4                                 *)
(* ------------------------------------------------------------------ *)

(* Application of a reducible function to a reducible argument, at the
   identity weakening -- the form the [app_rel] congruence obligation
   consumes (compare Stlc/LogRel.v's [RV_apply]).

   NOTE how the syntactic-guard discipline pays off here.  The hypothesis
   is [RTm] at the SYNTACTIC Pi type, so [RTy_fun] plus inversion on the
   (unique) applicable clause hands back the Kripke property directly.  In
   the eq_term-guarded design this step would have required knowing that
   the Pi type is not convertible to [Nat] or to a neutral. *)
Lemma RTm_app_rel G rF F B f a
  : RTm G (iE oRel) (tEl G oRel (oPiRel G rF oL0 oL0 F B)) f ->
    RTm G (iE rF) (tEl G rF F) a ->
    EnvOk G -> NfCode G rF F -> NfCode (oExtC0 G rF F) oRel B ->
    RTmN G (iE oRel) (tCodAtR G rF F B G (oId G) a)
      (oAppRel G rF oL0 oL0 F B f a).
Admitted.

Lemma RTm_app_irr G rF F B f a
  : RTm G (iE oIrr) (tEl G oIrr (oPiIrr G rF oL0 F B)) f ->
    RTm G (iE rF) (tEl G rF F) a ->
    EnvOk G -> NfCode G rF F -> NfCode (oExtC0 G rF F) oIrr B ->
    RTmN G (iE oIrr) (tCodAtI G rF F B G (oId G) a)
      (oAppIrr G rF oL0 F B f a).
Admitted.

(* Introduction: a lambda whose body is reducible at every reducible
   argument is reducible.  This is where "Pi_rel beta" is used, and it is
   the ONLY place in the whole development where a beta step happens --
   everything else is discharged by the substitution equations of the
   theory itself. *)
Lemma RTm_lam_rel G rF F B t
  : EnvOk G -> NfCode G rF F -> NfCode (oExtC0 G rF F) oRel B ->
    (forall D w a, Wk D G w -> EnvOk D ->
        RTmN D (iE rF) (tDomAt G rF F D w) a ->
        RTmN D (iE oRel) (tCodAtR G rF F B D w a)
          (oExpSubst D (oExtC0 G rF F) (oSnocAt G rF F D w a) (iE oRel)
             (oEl (oExtC0 G rF F) oRel oL0 B) t)) ->
    RTm G (iE oRel) (tEl G oRel (oPiRel G rF oL0 oL0 F B))
      (oLamRel G rF oL0 oL0 F B t).
Admitted.

(* the same for the irrelevant Pi *)
Lemma RTm_lam_irr G rF F B t
  : EnvOk G -> NfCode G rF F -> NfCode (oExtC0 G rF F) oIrr B ->
    (forall D w a, Wk D G w -> EnvOk D ->
        RTmN D (iE rF) (tDomAt G rF F D w) a ->
        RTmN D (iE oIrr) (tCodAtI G rF F B D w a)
          (oExpSubst D (oExtC0 G rF F) (oSnocAt G rF F D w a) (iE oIrr)
             (oEl (oExtC0 G rF F) oIrr oL0 B) t)) ->
    RTm G (iE oIrr) (tEl G oIrr (oPiIrr G rF oL0 F B))
      (oLamIrr G rF oL0 F B t).
Admitted.
