Set Implicit Arguments.

From coqutil Require Import Datatypes.String.
From Stdlib Require Import Lists.List.
Import ListNotations.
Open Scope string.
Open Scope list.
From Utils Require Import Utils.
From Pyrosome Require Import Theory.Core Tools.ComputeWf Tools.Matches
  Tools.EGraph.ComputeWf.
From Pyrosome.Lang.OTT Require Import Base Nat.
Require Import WIP.DttPiNoEta.
Import Core.Notations.

(* =====================================================================
   DTT NORMALIZATION, LAYER 0: the target language and its index syntax.

   This is the analogue of Gluing/Stlc/Syntax.v for the dependent theory of
   src/Pyrosome/Lang/OTT/.  It is a SKELETON: every Definition/Inductive
   typechecks; lemma statements are Admitted.  Nothing here is imported by
   src/, and WIP/ is not part of the build.

   TARGET LANGUAGE.  [ott_dtt] is
       ott_pi_noeta ++ ott_nat ++ ott_base ++ subst_ott ++ ott_info
   i.e. Lang/OTT's Tarski-universe core (U/El, two levels, relevance tags),
   the parameterized substitution calculus, Nat/zero/suc/Empty/Emptyrec, and
   dependent Pi (relevant + irrelevant) with beta and the substitution
   commutations -- MINUS the "Pi_rel eta" rule.

   Why minus eta: Lang/OTT/Pi.v adds that rule with [push_rule_todo], which
   discharges its wf obligation with Tools/Interactive.v's [Axiom todo].  So
   [ott_pi] is axiom-dirty, and [tl ott_pi] is the largest axiom-free prefix.
   Dropping eta is also what keeps reification untyped (see the design doc).

   Why Nat is in: exactly the [unit_lang] situation of the STLC proof.  The
   only closed codes of [U r l] are Nat, Empty and Pi-of-codes; without a
   base code the universe is empty, [El A] is uninhabited for every A, and
   the normalization statement is vacuous.  Nat is the base case.

   SHAPES.  Every constructor's argument order below was read off the
   COMPILED language (rule contexts are stored most-recent-first and [con]'s
   argument list follows that order), not off the surface notation.  They were
   verified by [Eval vm_compute] on [named_map summ ott_core]; see the design
   doc for the dump.  Note in particular:
     - [snoc]'s con list is [v;g;A;i;G';G]  (v BEFORE g, unlike the STLC
       language where it was [v;A;g;G';G]);
     - [hd], [wkn], [id], [forget], [emp] carry their index arguments in the
       con list even though their [args] fields are empty;
     - [Empty] and [Pi_irr] are elaborated at info [rel (iota L1)], while
       [Nat] is elaborated at info [rel (next L0)] -- the two are equal only
       via the "next0" equation.  This is the smallest witness that
       [Ceq_sort] cannot be [eq].
   ===================================================================== *)

Notation term := (@term string).
Notation sort := (@sort string).
Notation ctx := (@ctx string).
Notation lang := (@lang string).

(* ------------------------------------------------------------------ *)
(* The language                                                         *)
(* ------------------------------------------------------------------ *)

(* [ott_pi_noeta = tl ott_pi] is defined in WIP/DttPiNoEta.v rather than here.
   That file exists only to isolate a HINT-DATABASE hazard: Lang/OTT/Pi.v
   exports [ott_pi_entry : wf_lang_ext _ ott_pi] into [wf_lang_db], and that
   entry rests on [Interactive.todo].  With Pi.v imported, [compute_wf_lang]
   picks the entry up opportunistically and every language wf proof in the
   file comes out axiom-dirty -- even for languages that do not contain the
   eta rule (verified: [wf_lang (ott_nat ++ ott_base ++ subst_ott ++
   ott_info)] is dirty with Pi imported, clean without).  Requiring
   DttPiNoEta (which does not Export Pi) gives us the VALUE without the
   hint, and [ott_dtt_wf] below is then axiom-free. *)

Definition ott_dtt : lang := Eval vm_compute in
  (ott_pi_noeta ++ ott_nat ++ ott_base ++ subst_ott ++ ott_info).

(* 68 rules: 32 term_rule, 27 term_eq_rule, 9 sort_rule, 0 sort_eq_rule.
   The last figure is the single most consequential fact about this
   language: it has NO sort equations at all.  Sorts are indexed by TERMS
   ([ty G i], [exp G i A]) and all "type equality" of the object theory is
   term equality at the sort [ty].  Consequently the [csort_by] obligation of
   CutTModel_ok is VACUOUS, and [Ceq_sort] is generated by [csort_cong]
   alone -- but is still not [eq], because [Ceq_term] at [ty] is not [eq].

   PROVED, and axiom-free ([Print Assumptions] = "Closed under the global
   context").  This is the only real proof in the skeleton. *)
Lemma ott_dtt_wf : wf_lang ott_dtt.
Proof. compute_wf_lang. Qed.

(* ------------------------------------------------------------------ *)
(* Sorts                                                                *)
(* ------------------------------------------------------------------ *)

Definition sRelevance : sort := scon "relevance" [].
Definition sLvl : sort := scon "lvl" [].
Definition sTlvl : sort := scon "tlvl" [].
Definition sInfo : sort := scon "tyinfo" [].
Definition sLtl (a b : term) : sort := scon "ltl" [b; a].
Definition sEnv : sort := scon "env" [].
Definition sSub (G G' : term) : sort := scon "sub" [G'; G].
Definition sTy (G i : term) : sort := scon "ty" [i; G].
Definition sExp (G i A : term) : sort := scon "exp" [A; i; G].

(* ------------------------------------------------------------------ *)
(* Term constructors                                                    *)
(* ------------------------------------------------------------------ *)

(* --- ott_info: relevance / levels / type-levels / the bundle --- *)
Definition oRel : term := con "rel" [].
Definition oIrr : term := con "irr" [].
Definition oL0 : term := con "L0" [].
Definition oL1 : term := con "L1" [].
Definition oLt01 : term := con "L0<L1" [].
Definition oIota (l : term) : term := con "iota" [l].
Definition oInf : term := con "inf" [].
Definition oNext (l : term) : term := con "next" [l].
Definition oInfo (r l : term) : term := con "info" [l; r].

(* --- subst_ott: the substitution calculus, parameterized by tyinfo --- *)
Definition oEmp : term := con "emp" [].
Definition oExt (G i A : term) : term := con "ext" [A; i; G].
Definition oId (G : term) : term := con "id" [G].
Definition oForget (G : term) : term := con "forget" [G].
Definition oCmp (G1 G2 G3 f g : term) : term := con "cmp" [g; f; G3; G2; G1].
Definition oTySubst (G G' g i A : term) : term :=
  con "ty_subst" [A; i; g; G'; G].
Definition oExpSubst (G G' g i A v : term) : term :=
  con "exp_subst" [v; A; i; g; G'; G].
Definition oSnoc (G G' i A g v : term) : term := con "snoc" [v; g; A; i; G'; G].
Definition oWkn (G i A : term) : term := con "wkn" [A; i; G].
Definition oHd (G i A : term) : term := con "hd" [A; i; G].

(* --- ott_base: the Tarski universe --- *)
Definition oU (G r l : term) : term := con "U" [l; r; G].
Definition oEl (G r l e : term) : term := con "El" [e; l; r; G].

(* --- ott_nat --- *)
Definition oNat (G : term) : term := con "Nat" [G].
Definition oZero (G : term) : term := con "zero" [G].
Definition oSuc (G n : term) : term := con "suc" [n; G].
Definition oEmpty (G : term) : term := con "Empty" [G].
Definition oEmptyrec (G rA lA A e : term) : term :=
  con "Emptyrec" [e; A; lA; rA; G].

(* --- ott_pi --- *)
Definition oPiRel (G rF lF lG F B : term) : term :=
  con "Pi_rel" [B; F; lG; lF; rF; G].
Definition oPiIrr (G rF lF F B : term) : term :=
  con "Pi_irr" [B; F; lF; rF; G].
Definition oLamRel (G rF lF lG F B t : term) : term :=
  con "lam_rel" [t; B; F; lG; lF; rF; G].
Definition oLamIrr (G rF lF F B t : term) : term :=
  con "lam_irr" [t; B; F; lF; rF; G].
Definition oAppRel (G rF lF lG F B f a : term) : term :=
  con "app_rel" [a; f; B; F; lG; lF; rF; G].
Definition oAppIrr (G rF lF F B f a : term) : term :=
  con "app_irr" [a; f; B; F; lF; rF; G].

(* ------------------------------------------------------------------ *)
(* Derived abbreviations that recur in the rules' conclusion sorts       *)
(* ------------------------------------------------------------------ *)

(* The info of a code at level [l]: [rel, next l]. *)
Definition iCode (l : term) : term := oInfo oRel (oNext l).
(* The info of an element of a type at relevance [r], level [l]. *)
Definition iEl (r l : term) : term := oInfo r (oIota l).

(* [sCode G r l] : the sort of codes for [r,l]-types in [G]. *)
Definition sCode (G r l : term) : sort := sExp G (iCode l) (oU G r l).
(* [sEl G r l e] : the sort of elements of the type named by the code [e]. *)
Definition sEl (G r l e : term) : sort := sExp G (iEl r l) (oEl G r l e).

(* The context extension by the type named by a code (the shape every binder
   rule uses): [ext G (info rF (iota lF)) (El G rF lF F)]. *)
Definition oExtC (G rF lF F : term) : term :=
  oExt G (iEl rF lF) (oEl G rF lF F).

(* The instantiating substitution [<id, a> : sub G (extC G rF lF F)], as it
   appears in [app_rel]'s conclusion sort. *)
Definition oInst (G rF lF F a : term) : term :=
  oSnoc G G (iEl rF lF) (oEl G rF lF F) (oId G) a.

(* [app_rel]'s conclusion sort, verbatim from the compiled rule. *)
Definition sAppRelConcl (G rF lF lG F B : term) : sort :=
  sExp G (iEl oRel lG)
    (oTySubst G (oExtC G rF lF F) (oInst G rF lF F (con "a" []))
       (iEl oRel lG) (oEl (oExtC G rF lF F) oRel lG B)).

(* ------------------------------------------------------------------ *)
(* Index normal forms                                                   *)
(*                                                                      *)
(* [relevance] and [lvl] are rigid (no equations, two closed constructors *)
(* each).  [tlvl] has the two equations "next0" ([next L0 = iota L1]) and *)
(* "next1" ([next L1 = inf]); its normal forms are therefore exactly      *)
(* [iota L0], [iota L1], [inf] -- a THREE-element set.  [tyinfo] has one  *)
(* constructor, so its normal forms are the six [info r n].              *)
(*                                                                      *)
(* [ntlvl]/[ninfo] below are total normalizers on the index syntax; they  *)
(* are what [Ceq_term] uses at these sorts, so that index equality is     *)
(* DECIDED rather than carried.                                          *)
(* ------------------------------------------------------------------ *)

Inductive RelNf : term -> Prop :=
| relnf_rel : RelNf oRel
| relnf_irr : RelNf oIrr.

Inductive LvlNf : term -> Prop :=
| lvlnf_L0 : LvlNf oL0
| lvlnf_L1 : LvlNf oL1.

Inductive TlvlNf : term -> Prop :=
| tlvlnf_iota : forall l, LvlNf l -> TlvlNf (oIota l)
| tlvlnf_inf : TlvlNf oInf.

Inductive InfoNf : term -> Prop :=
| infonf : forall r n, RelNf r -> TlvlNf n -> InfoNf (oInfo r n).

(* The normalizer.  [next L0 = iota L1] and [next L1 = inf] are the only
   tlvl equations, so this is a one-step rewrite. *)
Definition ntlvl (n : term) : term :=
  match n with
  | con "next" [l] =>
      match l with
      | con "L0" [] => oIota oL1
      | con "L1" [] => oInf
      | _ => n
      end
  | _ => n
  end.

Definition ninfo (i : term) : term :=
  match i with
  | con "info" [n; r] => oInfo r (ntlvl n)
  | _ => i
  end.

Lemma ntlvl_nf n : TlvlNf (ntlvl n) \/ ntlvl n = n.
Admitted.

Lemma ninfo_idem i : ninfo (ninfo i) = ninfo i.
Admitted.

(* The soundness/completeness of the index normalizer against the theory.
   Soundness is by the two equations; completeness (the converse) is one of
   the RIGIDITY facts, and is proved by an auxiliary CutTModel (see
   WIP/DttRigidity.v in the design doc's Layer 0.5), not here. *)
Lemma ntlvl_sound n
  : wf_term ott_dtt [] n sTlvl -> eq_term ott_dtt [] sTlvl n (ntlvl n).
Admitted.

Lemma ninfo_sound i
  : wf_term ott_dtt [] i sInfo -> eq_term ott_dtt [] sInfo i (ninfo i).
Admitted.

Lemma ninfo_complete i1 i2
  : wf_term ott_dtt [] i1 sInfo ->
    wf_term ott_dtt [] i2 sInfo ->
    eq_term ott_dtt [] sInfo i1 i2 ->
    ninfo i1 = ninfo i2.
Admitted.
