(* ===================================================================== *)
(* WIP scratch: discharging [reflect_pi_reify_step] (LogRelFund.v).         *)
(* NOT in the build (WIP/ is excluded from _CoqProject).                    *)
(*                                                                         *)
(* Session 2026-06-05 findings (see memory logrel-pi-reify-obstruction):    *)
(*                                                                         *)
(* The goal of [reflect_pi_reify_step] is, given the eta-body [body]         *)
(* reflecting [nApp (shift n) ARG] at the GENERIC-arg codomain              *)
(* [posTy PA ra0] (with [rb : redTm (posPack PA ra0) body]), and a renaming *)
(* [sg] + reducible arg [a]:                                                *)
(*     { v & Apply_val (len Delta) (a :: id_list) bodysg v                  *)
(*           * redTm (posPack PA ra) v }.                                    *)
(* By [Apply_beta_merge] the witness [v] is FORCED to be the beta-reduct    *)
(* [body[a::sg]] (Apply is deterministic).  So the real content is:         *)
(*     redTm (posPack PA ra) (body[a::sg]).                                  *)
(*                                                                         *)
(* OBSTRUCTION (a) -- the recorded "Reflect_det" assembly is INCOMPLETE for  *)
(* higher-order / universe-dependent codomains.  Counterexample inside the   *)
(* finite tower: the relevant Pi  [∀ (X : U_tl1). El X]  (F = a universe     *)
(* code, B = El(var0)).  Then ARG = reflect(var0 @ universe) = vNe(nVar 0)   *)
(* (refl_U), so posTy PA ra0 = El(vNe(nVar0)) is a NEUTRAL-El and            *)
(* body = vNe(nApp (shift n) (vNe nVar0)) is a BARE NEUTRAL.  For a = a      *)
(* Pi-code [vPi G C], posTy PA ra = El(vPi G C) is a RELEVANT Pi, whose      *)
(* reflection eta-EXPANDS to a vLam.  Hence body[a::sg] = vNe(..) is a bare  *)
(* neutral that does NOT even reflect at posTy PA ra (refl_Pi forces vLam).  *)
(* So [body[a::sg] = v*] (Reflect_det vs the IHpos reflection) is FALSE.     *)
(* body[a::sg] is still REDUCIBLE there (a neutral is reducible at a Pi via  *)
(* its application clause), but that reducibility is recursively            *)
(* [reflect_red]'s own content at the codomain -- it is NOT the syntactic    *)
(* eta-long [v*].  The bridge must be UP-TO-LR (eta-irrelevance), which the  *)
(* current [LR] has no principle for (cf. memory                            *)
(* logrel-pack-weakening-delegation: "no irrelevance principle").           *)
(*                                                                         *)
(* OBSTRUCTION (b) -- [Reflect_ren]'s hypothesis [ren_ok rho (S m) m2] is    *)
(* load-bearing (its codomain step uses [Apply_val_ren_commute] at level    *)
(* [S m], needing [ren_ok] up to [S(S m)] via [ren_ok_up]; tightening to    *)
(* [ren_ok rho m m2] breaks that step -- verified this session).  For the    *)
(* reify use ([up sg] on Hbody at m = S(len Ge)) the boundary out-of-range   *)
(* index forces [len Ge < len Delta], i.e. only STRICTLY-growing renamings.  *)
(* Surmountable by PADDING the rho list (body is scoped < S(len Ge), so      *)
(* ren_val is insensitive to the padded entry) -- not fundamental.           *)
(*                                                                         *)
(* OBSTRUCTION (c) -- [wf_senv Delta] is needed to invoke [IHpos]            *)
(* (reflect_motive starts [wf_senv Delta -> ...]) but is NOT derivable from  *)
(* the reify_step hypotheses (wf_ssub does not carry it; no presupposition   *)
(* lemma has_svalty/wf_neutral -> wf_senv exists).  Likely a MISSING         *)
(* HYPOTHESIS on reflect_pi_reify_step, or must be threaded from the         *)
(* PiRedTmPred clause / derived from reducibility.                           *)
(*                                                                         *)
(* CONCLUSION: the genuine remaining content is a RESTRICTED RedSub-closure  *)
(* (reducibility transported under [a :: sg] = reducible-arg cons onto a     *)
(* renaming) PLUS reducibility-eta-irrelevance, and for higher-order         *)
(* domains it is MUTUALLY ENTANGLED with [reflect_red] (the codomain bare    *)
(* neutral's reducibility is reflect_red's job at the codomain).  This is a  *)
(* multi-session VR-layer effort, not closable by Reflect_det + IHpos.       *)
(*                                                                         *)
(* PROVEN STRUCTURAL PREFIX (reusable):                                      *)
(*   destruct rn as [rho Hrho].                                              *)
(*   assert (Hbodysg : bodysg = ren_val (up_renl rho) body).                 *)
(*   { apply (fst (snd Apply_ren_eq) (S (length Delta)) (up_renl rho)).      *)
(*     unfold ren_sub. rewrite <- up_ren_sub, <- Hrho. exact bs. }           *)
(* ===================================================================== *)
